[EUR_USD]
price = 1.2
spread = 0.002
tick_size = 0.0001
[EUR_USD.market_simulator]
	model = "fodra-pham"
	bid_volume = 1000
    ask_volume = 1000
	alpha_plus = 0.2
	alpha_neg = 0.2
	tick_probs = [0.1, 0.3, 0.2, 0.1, 0.1, 0.1, 0.1]
			
[AUD_USD]
price = 0.78
spread = 0.002
tick_size = 0.0001
[AUD_USD.market_simulator]
	model = "fodra-pham"
	bid_volume = 1000
    ask_volume = 1000
	alpha_plus = 0.2
	alpha_neg = 0.2
	tick_probs = [0.1, 0.3, 0.2, 0.1, 0.1, 0.1, 0.1]